export const GET_ALL_PHOTOS_REQUESTED = 'GET_ALL_PHOTOS_REQUESTED';
export const GET_ALL_PHOTOS_SUCCESS = 'GET_ALL_PHOTOS_SUCCESS';
export const GET_ALL_PHOTOS_FAILED = 'GET_ALL_PHOTOS_FAILED';

export const SELECT_PHOTO = 'SELECT_PHOTO';

export const ADD_PHOTOS_REQUESTED = 'ADD_PHOTOS_REQUESTED';
export const ADD_PHOTOS_SUCCESS = 'ADD_PHOTOS_SUCCESS';
export const ADD_PHOTOS_FAILED = 'ADD_PHOTOS_FAILED';